# Setup
title:               Down to the Wire
description:         A site by Joe Friedrichsen
url:                 https://downtothewire.io
baseurl:             ''
permalink:           pretty
livereload:          true
exclude:             [CNAME, Gemfile, README.md, LICENSE]

# Colors
remote_theme:        piazzai/hacked-jekyll
color_bg:            gray-9
color_punct:         gray-6
color_key:           yellow-4
color_value:         yellow-4
color_hover:         violet-4

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-remote-theme

sass:
  sourcemap: never
  verbose:   true
