# Permalinks
permalink:           pretty

# Setup
exclude:             [CNAME, Gemfile, README.md, LICENSE.md, scratch.md]
unpublished:         true
show_drafts:         false
title:               Down to the Wire
tagline:             Elements of Data Acquisition
description:         'A blog by Joe Friedrichsen'
url:                 https://downtothewire.io
baseurl:             ''

# About/contact
author:
  name:              Joe Friedrichsen
  url:               https://github.com/wireddown
  email:             all.wired.down@gmail.com

# Custom data
established:         2014
license:             CC BY 4.0
license_url:         https://creativecommons.org/licenses/by/4.0/legalcode
